<li style="overflow:hidden;width:100%;height:85px;">
					<h2 style="overflow:hidden;width:100%;height:25px;line-height:25px;float:left;overflow:hidden;text-overflow:ellipsis;white-space: nowrap;">
						<a href="[field:arcurl/]" target="_blank" title="[field:title/]" style="color:#333;font-size:14px;">Q:[field:title/]</a>
					</h2>
					<p style="overflow:hidden;height:55px;margin:5px auto;width:100%;text-align:left;">
						<a href="[field:arcurl/]" target="_blank" title="[field:title/]" style="color:#333;font-size:14px;">A:[field:description function='cn_substr(@me,200)'/] ...
						</a>
					</p>
				</li>