<a href="[field:arcurl/]" style="width:23%;margin:0 1%;height:510px;display:block;float:left;">
			<img  style="width:100%;height:250px" SRC="[field:picname/]"/>
			<p style="overflow:hidden;line-height:25px;margin:10px auto;width:98%;height:100px;color:#333;font-size:16px;">
				<b>[field:description/]</b>
			</p>
			<p style="height:150px;margin:10px auto;width:98%;text-align:center;">
				<img style="width:200px;height:40px;margin:20px auto;" SRC="/templets/my/images/xqan.jpg"/>
			</p>
		</a>