<field:pagestyle itemname="页面风格" type="number" isnull="true" default="2" rename="" notsend="1" />	
<field:imgurls itemname="图片集合" type="img" isnull="true" default="" rename="" page="split"/>	
<field:body itemname="图集内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page=""></field:body>
<field:trueprice itemname="优惠价" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:trueprice>
<field:units itemname="计量单位" autofield="0" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:units>
<field:price itemname="市场价" autofield="0" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:price>
<field:brand itemname="品牌" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:brand>


<field:price_a itemname="价格" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:price_a>

<field:units_s itemname="单位" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:units_s>
