<divstyle="width:23%;margin:0 1%;height:auto;overflow:hidden;display:block;float:left;">
					<a href="[field:arcurl/]" ><img  style="width:100%;height:250px" SRC="[field:picname/]"/></a>
					
					<p style="overflow:hidden;line-height:25px;margin:10px auto;width:98%;height:100px;color:#333;font-size:16px;text-align:center;">
						<a href="[field:arcurl/]" ><b>[field:title/]</b></a>
					</p>
				</div>