<li style="overflow:hidden;width:100%;height:135px;margin-bottom:30px;">
					<img  style="width:30%;height:135px;float:left;margin-right:10px;" SRC="[field:picname/]"/>
					<h2 style="overflow:hidden;width:58%;height:30px;float:left;overflow:hidden;text-overflow:ellipsis;white-space: nowrap;">
						<a href="[field:arcurl/]" target="_blank" title="[field:title/]" style="color:#333;font-size:14px;">[field:title/]</a>
					</h2>
					<p style="overflow:hidden;height:120px;margin:5px auto;width:66%;text-align:left;">
						<a href="[field:arcurl/]" target="_blank" title="[field:title/]" style="color:#999;font-size:14px;">[field:description/]
						</a>
					</p>
				</li>