<a href="[field:arcurl/]" style="width:31%;margin:0 1%;height:350px;display:block;float:left;">
				<img  style="width:100%;height:250px" SRC="[field:picname/]"/>
				<p style="overflow:hidden;text-overflow:ellipsis;white-space: nowrap;line-height:25px;margin:10px auto;width:98%;height:30px;color:#333;font-size:16px;">
					<b>[field:title/]</b>
				</p>
				<p style="height:30px;margin:10px auto;width:98%;text-align:left;">
					<img style="width:20px;height:20px;margin:0 5px;float:left;" SRC="/templets/my/images/date.jpg"/>[field:pubdate function="GetDateTimeMK(@me)" /]
				</p>
			</a>