<?php
$z[0]=Array("arcurl","",105,120);
$z[0][4]=array();
$z[1]=Array("picname","",166,182);
$z[1][4]=array();
$z[2]=Array("typelink","",334,351);
$z[2][4]=array();
$z[3]=Array("arcurl","",515,530);
$z[3][4]=array();
$z[4]=Array("title","",555,569);
$z[4][4]=array();
$z[5]=Array("price","",789,803);
$z[5][4]=array();
$z[6]=Array("units","",807,821);
$z[6][4]=array();
$z[7]=Array("id","\r\n\$aid = @me;\r\n\$row = \$GLOBALS['dsql']->GetOne(\"SELECT `trueprice` FROM  `#@__addonshop` where aid='\$aid' \");\r\n@me = \"{\$row['trueprice']}尽快解决\";\r\n",984,1171);
$z[7][4]=array();
$z[7][4]['runphp']="yes";
$z[8]=Array("price","",1242,1256);
$z[8][4]=array();
$z[9]=Array("units","",1260,1274);
$z[9][4]=array();
$z[10]=Array("arcurl","",1433,1448);
$z[10][4]=array();

?>