<?php
$z[0]=Array("global","",1503,1535);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("flinktype","\r\n						{dede:flink/}\r\n					",1705,1791);
$z[1][4]=array();
$z[1][4]['typeid']="1";
$z[1][4]['linktype']="2";
$z[2]=Array("global","",1895,1927);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2042,2068);
$z[3][4]=array();
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",2117,2143);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",2233,2257);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";

?>