<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="header_top"style="width:80%;min-width:1200px;margin:0 auto;text-align:center;height:80px !important;line-height:80px;background:#fff;border:none">  
    <div class="center"style="width:100%;min-width:1200px;margin:0 auto;text-align:center;">  
     <span id="time" class="time"style="font-size:16px;">欢迎光临<?php echo $GLOBALS['cfg_webname']; ?></span>
		<div class="toplinks"style="font-size:16px;color:#333;">
			<span style="color:red;">咨询电话：<?php echo $GLOBALS['tel']; ?></span>
			手机官网
		</div>
    </div> 
</div>

<div class="header" style="width:80%;min-width:1200px;margin:0 auto;text-align:center">
	<div class="center" style="height:auto;width:100%;overflow:hidden">
      <div class="title" style="width:100%;height:auto;overflow:hidden;">
        <h1  style="width:25%;height:100%;float:left;overflow:hidden;"><a  style="height:100%;width:100%"href="<?php echo $GLOBALS['cfg_basehost']; ?>"><img src="<?php echo $GLOBALS['cfg_templets_skin']; ?>/images/logo.gif" style="width:100%;height:100%" alt="<?php echo $GLOBALS['cfg_webname']; ?>"/></a> 
		</h1>
		<div style="width:74%;float:right;height:100px!important;overflow:hidden;">
			<div style="text-align:left;line-height:138px;width:50%;height:100px;float:left;overflow:hidden;">
				<span style="font-size:22px;margin:0 10px;"><a href="/a/fengongsi"><span id="city">广州总部</span>▼</a></span>
				<strong style="font-size:1.5rem;color:red;">建筑装修装饰工程专业承包壹级</strong>
			</div>
			<div style="width:40%;height:100px;float:right;overflow:hidden">
				
				<div style="width:auto;height:100px;float:right;overflow:hidden;text-align:right;">
					<img src="<?php echo $GLOBALS['cfg_templets_skin']; ?>/images/tel24_7.png" style="margin:12px 15px 0 0;width:80px;height:80px;float:left"/>
					<span style="width:auto;display:block;height:50px;margin:0 auto;overflow:hidden;text-align:left;line-height:50px;font-size:30px;color:red;"><?php echo $GLOBALS['tel']; ?></span>
					
					<span style="width:auto;display:block;height:40px;margin:0 auto;overflow:hidden;text-align:left;line-height:40px;font-size:22px;color:#333;">全国免费咨询热线</span>
					
				</div>
			</div>
		</div>
		
	  </div>
	</div><!-- //top -->
	
</div><!-- //header -->

<!-- //菜单 -->
	<div class="module blue mT10 wrapper w963" style="background:#cc3636;width:100%;min-width:1200px;margin:20px auto;text-align:center">
		<div class="top" style="width:90%;max-width:1200px;*padding:10px;height:45px;background:#cc3636;margin:0 auto;">
			<!-- //如果不使用currentstyle，可以在channel标签加入 cacheid='channeltoplist' 属性提升性能 -->
			<div style="width:100%;background:#cc3636;height:45px!important;line-height:45px;padding:0;">
				
					
						<a href='/' style="overflow:hidden;color:#fff;font-size:22px;lmargin:0 28px;">
							<span>主页</span>
						</a>
					
					
					<!--
					<li style="margin:0 20px;height:45px;"><a href='/a/guanyuwomen/'  rel='dropmenu1'><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">关于我们</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/bangongshitaocan/'  rel='dropmenu2'><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">办公室套餐</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/jiazhuangtaocan/'  rel='dropmenu3'><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">家装套餐</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/jidiananzhuang/'  rel='dropmenu4'><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">机电安装</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/xiangmuhezuo/' ><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">项目合作</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/weixiuyewu/' ><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">维修业务</span></a></li>
					
					<li style="margin:0 20px;height:45px;"><a href='/a/fengongsi/' ><span style="height:45px;overflow:hidden;line-height:40px;font-size:18px;*line-height:-50px;">分公司</span></a></li>
					-->
					
						<a href='/a/guanyuwomen/gongsijianjie' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>关于我们</span>
						</a>
					
					
					
						<a href='/a/528taocan/' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>办公室套餐</span>
						</a>
					
					
					
						<a href='/a/jiazhuangtaocan' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>家装套餐</span>
						</a>
					
					
					
						<a href='/a/jidiananzhuang/nuantongkongdiaoanzhuang' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>机电安装</span>
						</a>
					
					
					
						<a href='/a/xiangmuhezuo' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>项目合作</span>
						</a>
				
					
					
						<a href='/a/weixiuyewu' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>维修业务</span>
						</a>
					
					
					
						<a href='/a/fengongsi' style="overflow:hidden;color:#fff;font-size:22px;margin:0 37px;">
							<span>分公司</span>
						</a>
					
				
				
					
			</div>	
    
		</div>
	</div>
<script type="text/javascript" src="<?php echo $GLOBALS['cfg_templets_skin']; ?>/js/jquery-2.1.1.min.js"></script>
<script type="text/javascript" src="<?php echo $GLOBALS['cfg_templets_skin']; ?>/js/jquery.cookie.js"></script>
<script type="text/javascript">
$(function (){
	//var vals = $.cookie('city_cookie'); 
	var vals = getCookie('city_cookie'); 
	//vals = "广州总部";
	if(vals == "" || vals == null){
		vals = "广州总部";
	}
	
	$("#city").html(vals);
	
});

function getCookie(name)
{
	var arr,reg=new RegExp("(^| )"+name+"=([^;]*)(;|$)");
	if(arr=document.cookie.match(reg)){
		return unescape(arr[2]);
	}else{
		return null;
	}
}
</script>